#!/bin/bash

deepspeed --include localhost:0,1 llava/train/train_mem.py \
    --lora_enable True --lora_r 16 --lora_alpha 32 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /data2/yubowang/llava1.5-7b \
    --version v1 \
    --data_path /data2/yubowang/TextVQA/text_vqa_output.json \
    --image_folder /data2/yubowang/TextVQA/train_images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /data2/yubowang/llava_lora_ckpt3_textvqa_rank16_epoch3 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
